In [270]:
import pandas as pd
import numpy as np

In [271]:
train = pd.read_csv('/home/alvoritmo/Escritorio/MachineLearning/data/train.csv')
test = pd.read_csv('/home/alvoritmo/Escritorio/MachineLearning/data/test.csv')

In [272]:
train.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca  thal  num  
0    3.0  0.0   6.0    0  
1    2.0  3.0   3.0    2  
2    2.0  2.0   7.0    1  
3    3.0  0.0   3.0    0  
4    1.0  0.0   3.0    0

In [273]:
train.head(22)

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0   63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1   67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2   67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3   37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4   41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   
5   56.0  1.0  2.0     120.0  236.0  0.0      0.0    178.0    0.0      0.8   
6   62.0  0.0  4.0     140.0  268.0  0.0      2.0    160.0    0.0      3.6   
7   57.0  0.0  4.0     120.0  354.0  0.0      0.0    163.0    1.0      0.6   
8   63.0  1.0  4.0     130.0  254.0  0.0      2.0    147.0    0.0      1.4   
9   53.0  1.0  4.0     140.0  203.0  1.0      2.0    155.0    1.0      3.1   
10  57.0  1.0  4.0     140.0  192.0  0.0      0.0    148.0    0.0      0.4   
11  56.0  0.0  2.0     140.0  294.0  0.0      2.0    153.0    0.0      1.3   
12  56.0  1.0  3.0     130.0  256.0  1.0      2.0    142.0    1.0      0.6   
13  44.0  1.0  2.0     120.0  263.0  0.0      0.0    173.0    0.0      0.0   
14  52.0  1.0  3.0     172.0  199.0  1.0      0.0    162.0    0.0      0.5   
15  57.0  1.0  3.0     150.0  168.0  0.0      0.0    174.0    0.0      1.6   
16  48.0  1.0  2.0     110.0  229.0  0.0      0.0    168.0    0.0      1.0   
17  54.0  1.0  4.0     140.0  239.0  0.0      0.0    160.0    0.0      1.2   
18  48.0  0.0  3.0     130.0  275.0  0.0      0.0    139.0    0.0      0.2   
19  49.0  1.0  2.0     130.0  266.0  0.0      0.0    171.0    0.0      0.6   
20  64.0  1.0  1.0     110.0  211.0  0.0      2.0    144.0    1.0      1.8   
21  58.0  0.0  1.0     150.0  283.0  1.0      2.0    162.0    0.0      1.0   

    slope   ca  thal  num  
0     3.0  0.0   6.0    0  
1     2.0  3.0   3.0    2  
2     2.0  2.0   7.0    1  
3     3.0  0.0   3.0    0  
4     1.0  0.0   3.0    0  
5     1.0  0.0   3.0    0  
6     3.0  2.0   3.0    3  
7     1.0  0.0   3.0    0  
8     2.0  1.0   7.0    2  
9     3.0  0.0   7.0    1  
10    2.0  0.0   6.0    0  
11    2.0  0.0   3.0    0  
12    2.0  1.0   6.0    2  
13    1.0  0.0   7.0    0  
14    1.0  0.0   7.0    0  
15    1.0  0.0   3.0    0  
16    3.0  0.0   7.0    1  
17    1.0  0.0   3.0    0  
18    1.0  0.0   3.0    0  
19    1.0  0.0   3.0    0  
20    2.0  0.0   3.0    0  
21    1.0  0.0   3.0    0

In [274]:
train.describe()

age         sex          cp    trestbps        chol         fbs  \
count  264.000000  264.000000  264.000000  264.000000  264.000000  264.000000   
mean    54.382576    0.670455    3.155303  131.162879  250.367424    0.151515   
std      9.010843    0.470941    0.952548   17.871531   51.084265    0.359231   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  214.000000    0.000000   
50%     55.000000    1.000000    3.000000  130.000000  245.500000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  278.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  264.000000  264.000000  264.000000  264.000000  264.000000  262.000000   
mean     1.037879  150.015152    0.325758    1.016667    1.583333    0.671756   
std      0.997375   23.215140    0.469547    1.140120    0.617140    0.950440   
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000   
25%      0.000000  135.250000    0.000000    0.000000    1.000000    0.000000   
50%      2.000000  154.000000    0.000000    0.750000    2.000000    0.000000   
75%      2.000000  167.250000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000    3.000000   

             thal         num  
count  263.000000  264.000000  
mean     4.676806    0.901515  
std      1.945369    1.232388  
min      3.000000    0.000000  
25%      3.000000    0.000000  
50%      3.000000    0.000000  
75%      7.000000    2.000000  
max      7.000000    4.000000

In [275]:
test.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  61.0  1.0  4.0     138.0  166.0  0.0      2.0    125.0    1.0      3.6   
1  42.0  1.0  4.0     136.0  315.0  0.0      0.0    125.0    1.0      1.8   
2  52.0  1.0  4.0     128.0  204.0  1.0      0.0    156.0    1.0      1.0   
3  59.0  1.0  3.0     126.0  218.0  1.0      0.0    134.0    0.0      2.2   
4  40.0  1.0  4.0     152.0  223.0  0.0      0.0    181.0    0.0      0.0   

   slope   ca thal  
0    2.0  1.0  3.0  
1    2.0  0.0  6.0  
2    2.0  0.0    ?  
3    2.0  1.0  6.0  
4    1.0  0.0  7.0

In [277]:
test=test.replace('?',np.nan)
test=test.fillna(test.mean())
test=test.dropna()

In [278]:
display(test)

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0   61.0  1.0  4.0     138.0  166.0  0.0      2.0    125.0    1.0      3.6   
1   42.0  1.0  4.0     136.0  315.0  0.0      0.0    125.0    1.0      1.8   
3   59.0  1.0  3.0     126.0  218.0  1.0      0.0    134.0    0.0      2.2   
4   40.0  1.0  4.0     152.0  223.0  0.0      0.0    181.0    0.0      0.0   
5   42.0  1.0  3.0     130.0  180.0  0.0      0.0    150.0    0.0      0.0   
6   61.0  1.0  4.0     140.0  207.0  0.0      2.0    138.0    1.0      1.9   
7   66.0  1.0  4.0     160.0  228.0  0.0      2.0    138.0    0.0      2.3   
8   46.0  1.0  4.0     140.0  311.0  0.0      0.0    120.0    1.0      1.8   
9   71.0  0.0  4.0     112.0  149.0  0.0      0.0    125.0    0.0      1.6   
10  59.0  1.0  1.0     134.0  204.0  0.0      0.0    162.0    0.0      0.8   
11  64.0  1.0  1.0     170.0  227.0  0.0      2.0    155.0    0.0      0.6   
12  66.0  0.0  3.0     146.0  278.0  0.0      2.0    152.0    0.0      0.0   
13  39.0  0.0  3.0     138.0  220.0  0.0      0.0    152.0    0.0      0.0   
14  57.0  1.0  2.0     154.0  232.0  0.0      2.0    164.0    0.0      0.0   
15  58.0  0.0  4.0     130.0  197.0  0.0      0.0    131.0    0.0      0.6   
16  57.0  1.0  4.0     110.0  335.0  0.0      0.0    143.0    1.0      3.0   
17  47.0  1.0  3.0     130.0  253.0  0.0      0.0    179.0    0.0      0.0   
18  55.0  0.0  4.0     128.0  205.0  0.0      1.0    130.0    1.0      2.0   
19  35.0  1.0  2.0     122.0  192.0  0.0      0.0    174.0    0.0      0.0   
20  61.0  1.0  4.0     148.0  203.0  0.0      0.0    161.0    0.0      0.0   
21  58.0  1.0  4.0     114.0  318.0  0.0      1.0    140.0    0.0      4.4   
22  58.0  0.0  4.0     170.0  225.0  1.0      2.0    146.0    1.0      2.8   
24  56.0  1.0  2.0     130.0  221.0  0.0      2.0    163.0    0.0      0.0   
25  56.0  1.0  2.0     120.0  240.0  0.0      0.0    169.0    0.0      0.0   
26  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
27  55.0  0.0  2.0     132.0  342.0  0.0      0.0    166.0    0.0      1.2   
28  44.0  1.0  4.0     120.0  169.0  0.0      0.0    144.0    1.0      2.8   
29  63.0  1.0  4.0     140.0  187.0  0.0      2.0    144.0    1.0      4.0   
30  63.0  0.0  4.0     124.0  197.0  0.0      0.0    136.0    1.0      0.0   
31  41.0  1.0  2.0     120.0  157.0  0.0      0.0    182.0    0.0      0.0   
32  59.0  1.0  4.0     164.0  176.0  1.0      2.0     90.0    0.0      1.0   
33  57.0  0.0  4.0     140.0  241.0  0.0      0.0    123.0    1.0      0.2   
34  45.0  1.0  1.0     110.0  264.0  0.0      0.0    132.0    0.0      1.2   
35  68.0  1.0  4.0     144.0  193.0  1.0      0.0    141.0    0.0      3.4   
36  57.0  1.0  4.0     130.0  131.0  0.0      0.0    115.0    1.0      1.2   
37  57.0  0.0  2.0     130.0  236.0  0.0      2.0    174.0    0.0      0.0   

    slope   ca thal  
0     2.0  1.0  3.0  
1     2.0  0.0  6.0  
3     2.0  1.0  6.0  
4     1.0  0.0  7.0  
5     1.0  0.0  3.0  
6     1.0  1.0  7.0  
7     1.0  0.0  6.0  
8     2.0  2.0  7.0  
9     2.0  0.0  3.0  
10    1.0  2.0  3.0  
11    2.0  0.0  7.0  
12    2.0  1.0  3.0  
13    2.0  0.0  3.0  
14    1.0  1.0  3.0  
15    2.0  0.0  3.0  
16    2.0  1.0  7.0  
17    1.0  0.0  3.0  
18    2.0  1.0  7.0  
19    1.0  0.0  3.0  
20    1.0  1.0  7.0  
21    3.0  3.0  6.0  
22    2.0  2.0  6.0  
24    1.0  0.0  7.0  
25    3.0  0.0  3.0  
26    2.0  0.0  7.0  
27    1.0  0.0  3.0  
28    3.0  0.0  6.0  
29    1.0  2.0  7.0  
30    2.0  0.0  3.0  
31    1.0  0.0  3.0  
32    2.0  2.0  6.0  
33    2.0  0.0  7.0  
34    2.0  0.0  7.0  
35    2.0  2.0  7.0  
36    2.0  1.0  7.0  
37    2.0  1.0  3.0

In [282]:
lista_var=list(train)
var_predict = 'num'
lista_var.remove(var_predict)

In [8]:
train.num

0      0
1      2
2      1
3      0
4      0
5      0
6      3
7      0
8      2
9      1
10     0
11     0
12     2
13     0
14     0
15     0
16     1
17     0
18     0
19     0
20     0
21     0
22     1
23     3
24     4
25     0
26     0
27     0
28     0
29     3
      ..
234    0
235    3
236    2
237    1
238    0
239    0
240    0
241    0
242    0
243    2
244    0
245    2
246    2
247    1
248    3
249    0
250    0
251    1
252    0
253    0
254    0
255    0
256    0
257    0
258    0
259    1
260    0
261    3
262    0
263    0
Name: num, Length: 264, dtype: int64

In [9]:
train.iloc[21,2]

1.0

In [10]:
train.loc[21,'age']

58.0

In [11]:
train.shape

(264, 14)

In [12]:
nrow = train.shape[0]

In [13]:
nrow == len(train['num'])

True

In [14]:
nrow

264

In [15]:
train.num

0      0
1      2
2      1
3      0
4      0
5      0
6      3
7      0
8      2
9      1
10     0
11     0
12     2
13     0
14     0
15     0
16     1
17     0
18     0
19     0
20     0
21     0
22     1
23     3
24     4
25     0
26     0
27     0
28     0
29     3
      ..
234    0
235    3
236    2
237    1
238    0
239    0
240    0
241    0
242    0
243    2
244    0
245    2
246    2
247    1
248    3
249    0
250    0
251    1
252    0
253    0
254    0
255    0
256    0
257    0
258    0
259    1
260    0
261    3
262    0
263    0
Name: num, Length: 264, dtype: int64

In [16]:
train.num.unique()

array([0, 2, 1, 3, 4])

In [17]:
train.num.unique

<bound method Series.unique of 0      0
1      2
2      1
3      0
4      0
5      0
6      3
7      0
8      2
9      1
10     0
11     0
12     2
13     0
14     0
15     0
16     1
17     0
18     0
19     0
20     0
21     0
22     1
23     3
24     4
25     0
26     0
27     0
28     0
29     3
      ..
234    0
235    3
236    2
237    1
238    0
239    0
240    0
241    0
242    0
243    2
244    0
245    2
246    2
247    1
248    3
249    0
250    0
251    1
252    0
253    0
254    0
255    0
256    0
257    0
258    0
259    1
260    0
261    3
262    0
263    0
Name: num, Length: 264, dtype: int64>

In [18]:
for elemento in train.num:
    print('elemento')

elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
elemento
e

In [19]:
for i in range(nrow):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263


In [20]:
for i in range(nrow):
    if train['num'][i] == 0:
        print(train['num'][i])

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [21]:
for i in range(nrow):
    if train['num'][i] != 0:
        train.loc[i,'num'] = 1

In [22]:
train.num.unique()

array([0, 1])

In [23]:
from sklearn.preprocessing import Imputer

In [24]:
train.shape

(264, 14)

In [25]:
train.isnull()

age    sex     cp  trestbps   chol    fbs  restecg  thalach  exang  \
0    False  False  False     False  False  False    False    False  False   
1    False  False  False     False  False  False    False    False  False   
2    False  False  False     False  False  False    False    False  False   
3    False  False  False     False  False  False    False    False  False   
4    False  False  False     False  False  False    False    False  False   
5    False  False  False     False  False  False    False    False  False   
6    False  False  False     False  False  False    False    False  False   
7    False  False  False     False  False  False    False    False  False   
8    False  False  False     False  False  False    False    False  False   
9    False  False  False     False  False  False    False    False  False   
10   False  False  False     False  False  False    False    False  False   
11   False  False  False     False  False  False    False    False  False   
12   False  False  False     False  False  False    False    False  False   
13   False  False  False     False  False  False    False    False  False   
14   False  False  False     False  False  False    False    False  False   
15   False  False  False     False  False  False    False    False  False   
16   False  False  False     False  False  False    False    False  False   
17   False  False  False     False  False  False    False    False  False   
18   False  False  False     False  False  False    False    False  False   
19   False  False  False     False  False  False    False    False  False   
20   False  False  False     False  False  False    False    False  False   
21   False  False  False     False  False  False    False    False  False   
22   False  False  False     False  False  False    False    False  False   
23   False  False  False     False  False  False    False    False  False   
24   False  False  False     False  False  False    False    False  False   
25   False  False  False     False  False  False    False    False  False   
26   False  False  False     False  False  False    False    False  False   
27   False  False  False     False  False  False    False    False  False   
28   False  False  False     False  False  False    False    False  False   
29   False  False  False     False  False  False    False    False  False   
..     ...    ...    ...       ...    ...    ...      ...      ...    ...   
234  False  False  False     False  False  False    False    False  False   
235  False  False  False     False  False  False    False    False  False   
236  False  False  False     False  False  False    False    False  False   
237  False  False  False     False  False  False    False    False  False   
238  False  False  False     False  False  False    False    False  False   
239  False  False  False     False  False  False    False    False  False   
240  False  False  False     False  False  False    False    False  False   
241  False  False  False     False  False  False    False    False  False   
242  False  False  False     False  False  False    False    False  False   
243  False  False  False     False  False  False    False    False  False   
244  False  False  False     False  False  False    False    False  False   
245  False  False  False     False  False  False    False    False  False   
246  False  False  False     False  False  False    False    False  False   
247  False  False  False     False  False  False    False    False  False   
248  False  False  False     False  False  False    False    False  False   
249  False  False  False     False  False  False    False    False  False   
250  False  False  False     False  False  False    False    False  False   
251  False  False  False     False  False  False    False    False  False   
252  False  False  False     False  False  False    False    False  False   
253  False  False  False     False  False  False    False    False  False   
254

In [26]:
train.isnull().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca           True
thal         True
num         False
dtype: bool

In [27]:
train.isnull().any(1)

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
Length: 264, dtype: bool

In [28]:
train.loc[train.isnull().any(1)]

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
87   53.0  0.0  3.0     128.0  216.0  0.0      2.0    115.0    0.0      0.0   
166  52.0  1.0  3.0     138.0  223.0  0.0      0.0    169.0    0.0      0.0   
192  43.0  1.0  4.0     132.0  247.0  1.0      2.0    143.0    1.0      0.1   

     slope   ca  thal  num  
87     1.0  0.0   NaN    0  
166    1.0  NaN   3.0    0  
192    2.0  NaN   7.0    1

In [29]:
train = train.fillna(train.mean())

In [30]:
train.shape

(264, 14)

In [31]:
train.loc[train.isnull().any(1)]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, num]
Index: []

In [32]:
train.groupby("sex").sum()

age     cp  trestbps     chol   fbs  restecg  thalach  exang  oldpeak  \
sex                                                                             
0.0  4826.0  271.0   11584.0  23100.0  11.0     86.0  13234.0   18.0     75.7   
1.0  9531.0  562.0   23043.0  42997.0  29.0    188.0  26370.0   68.0    192.7   

     slope          ca        thal  num  
sex                                      
0.0  133.0   48.000000  314.676806   20  
1.0  285.0  129.343511  920.000000   95

In [33]:
train.groupby('sex').size()

sex
0.0     87
1.0    177
dtype: int64

In [236]:
from pandas.plotting import scatter_matrix

In [237]:
train.iloc[:,:-1].as_matrix()

array([[63.,  1.,  1., ...,  3.,  0.,  6.],
       [67.,  1.,  4., ...,  2.,  3.,  3.],
       [67.,  1.,  4., ...,  2.,  2.,  7.],
       ...,
       [58.,  0.,  2., ...,  1.,  2.,  3.],
       [60.,  0.,  1., ...,  1.,  0.,  3.],
       [44.,  1.,  3., ...,  1.,  0.,  3.]])

In [238]:
x, y = train.iloc[:,:-1].as_matrix(),train.iloc[:,-1].as_matrix()

In [239]:
train.shape

(264, 14)

In [240]:
x.shape

(264, 13)

In [241]:
y.shape

(264,)

In [242]:
print(x.ndim)

2


In [243]:
print(y.ndim)

1


In [244]:
x

array([[63.,  1.,  1., ...,  3.,  0.,  6.],
       [67.,  1.,  4., ...,  2.,  3.,  3.],
       [67.,  1.,  4., ...,  2.,  2.,  7.],
       ...,
       [58.,  0.,  2., ...,  1.,  2.,  3.],
       [60.,  0.,  1., ...,  1.,  0.,  3.],
       [44.,  1.,  3., ...,  1.,  0.,  3.]])

In [245]:
y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [246]:
from sklearn.model_selection import train_test_split

In [247]:
from sklearn.metrics import accuracy_score

In [248]:
from sklearn.ensemble import RandomForestClassifier

In [249]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.33,random_state = 42)

In [250]:
x_test

array([[59.,  1.,  4., ...,  3.,  0.,  7.],
       [68.,  0.,  3., ...,  2.,  0.,  3.],
       [39.,  1.,  3., ...,  1.,  0.,  3.],
       ...,
       [54.,  1.,  4., ...,  2.,  1.,  7.],
       [70.,  1.,  4., ...,  3.,  0.,  7.],
       [29.,  1.,  2., ...,  1.,  0.,  3.]])

In [251]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [252]:
clf = RandomForestClassifier(n_estimators=7,max_depth=None,min_samples_split=2,random_state=0)

In [253]:
clf

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=7, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [254]:
y_pred = clf.fit(x_train,y_train).predict(x_test)

In [255]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [284]:
num_predict = pd.DataFrame({ 'ID Paciente': test.index.tolist(),
                             'Num_Predict': y_pred })
display(num_predict)

ValueError: arrays must all be same length

In [256]:
from sklearn.metrics import confusion_matrix

In [257]:
cnf_matrix = confusion_matrix(y_test,y_pred)

In [258]:
cnf_matrix

array([[38,  6],
       [10, 34]])

In [259]:
pd.DataFrame(cnf_matrix,columns=['no','yes'],index=['no','yes'])

no  yes
no   38    6
yes  10   34

In [260]:
nsplit = 5
perc = 0.33

def traintest(nsplit, perc):
    results = []
    for i in range(nsplit):
        results_int = []
        
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=perc)
        clf = RandomForestClassifier(n_estimators=7, max_depth=None, min_samples_split=2, random_state=0)
        y_pred = clf.fit(x_train, y_train).predict(x_test)
        cnf_matrix = confusion_matrix(y_test, y_pred)
        
        results_int.append('------Item------')
        #results_int.append(X_train)
        #results_int.append(X_test)
        #results_int.append(y_train)
        #results_int.append(y_test)
        #results_int.append(y_pred)
        results_int.append(cnf_matrix)
        results.append(results_int)
    return results

traintest(nsplit, perc)

#Si añado: random_state=42 al train_test_split me salen siempre los mismos valores


[['------Item------', array([[35, 11],
         [12, 30]])], ['------Item------', array([[42,  9],
         [ 8, 29]])], ['------Item------', array([[43, 12],
         [ 7, 26]])], ['------Item------', array([[42,  5],
         [13, 28]])], ['------Item------', array([[37, 13],
         [ 7, 31]])]]

In [261]:
from sklearn.decomposition import PCA

In [262]:
pca = PCA(11)

In [263]:
xtr = pca.fit(x).transform(x)

In [264]:
x_train,x_test,y_train,y_test = train_test_split(xtr,y,test_size=0.33)

In [265]:
clf = RandomForestClassifier(n_estimators=7,max_depth=None,min_samples_split=2,random_state=0)

In [266]:
y_pred = clf.fit(x_train,y_train).predict(x_test)

In [267]:
cnf_matrix = confusion_matrix(y_test,y_pred)

In [268]:
pd.DataFrame(cnf_matrix,columns=['yes','no'],index=['yes','no'])

yes  no
yes   39   9
no    15  25

In [269]:
accuracy_score(y_test,y_pred)

0.7272727272727273